<<<<<<< HEAD:django-models/relationship_app/migrations/0001_initial.py
# Generated by Django 5.1 on 2024-08-27 09:40
||||||| 194c84c:django-models/LibraryProject/relationship_app/migrations/0001_initial.py
# Generated by Django 5.1 on 2024-08-23 09:51
=======
# Generated by Django 5.0.1 on 2024-08-26 13:53
>>>>>>> 0ff957ac8300fd4104bc3b9e59c611c3eed6dc4c:django-models/LibraryProject/relationship_app/migrations/0001_initial.py

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relationship_app.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("books", models.ManyToManyField(to="relationship_app.book")),
            ],
        ),
        migrations.CreateModel(
            name="Librarian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "library",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="relationship_app.library",
                    ),
                ),
            ],
        ),
    ]
